##---Game crate---##

[package]
name = "game"
version.workspace = true
edition.workspace = true

[lib]
path = "src/simulation/lib.rs"

[dependencies]
borger = { path = "borger/engine" }
log.workspace = true
glam.workspace = true
rapier3d.workspace = true





#the rest should Just Work™

##---Profiles---##

#dev build profile
[profile.server-dev]
inherits = "dev"
opt-level = 3 #optimize server for speed
[profile.client-dev]
inherits = "dev"
opt-level = "s" #optimize client for size

#release build profile: even more optimizations
[profile.release]
strip = "symbols" #no more debuggin
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "fat"
[profile.server-release]
inherits = "release"
opt-level = 3 #optimize server for speed
[profile.client-release]
inherits = "release"
opt-level = "s" #optimize client for size

[features]
server_internal_only_dont_use = ["borger/server"]
client_internal_only_dont_use = ["borger/client"]
session_replay = []

##---Workspace---##

[workspace]
resolver = "2"
members = [
	"borger/plugins/sdk/rs",
	"borger/engine",
	"borger/server",
	"borger/client/rs",
	"borger/procmac"
]

[workspace.package]
version = "0.0.0"
edition = "2024"

[workspace.dependencies]
log = { version = "*", default-features = false }
glam = { version = "*", default-features = false, features = ["std"] }
rapier3d = { version = "*", default-features = false, features = ["simd-nightly", "dim3", "f32", "alloc"] }
